drop table if exists authorities CASCADE;
drop table if exists clients CASCADE;
drop table if exists comments CASCADE;
drop table if exists orders CASCADE;
drop table if exists user_authorities CASCADE;
drop table if exists users CASCADE;
create table authorities (
   id bigint generated by default as identity,
    authority varchar(255),
    primary key (id)
);
create table clients (
   id bigint generated by default as identity,
    primary key (id)
);
create table comments (
   id bigint generated by default as identity,
    order_id bigint,
    primary key (id)
);
create table orders (
   id bigint generated by default as identity,
    status integer,
    client_id bigint,
    user_id bigint,
    primary key (id)
);
create table user_authorities (
   user_id bigint not null,
    authority_id bigint not null,
    primary key (user_id, authority_id)
);
create table users (
   id bigint generated by default as identity,
    account_non_expired boolean,
    account_non_locked boolean,
    credentials_non_expired boolean,
    enabled boolean,
    password varchar(255),
    username varchar(255),
    primary key (id)
);
alter table comments
   add constraint FKeii4ceows6il3vwttpv2tmbmo
   foreign key (order_id)
   references orders;
alter table orders
   add constraint FKm2dep9derpoaehshbkkatam3v
   foreign key (client_id)
   references clients;
alter table orders
   add constraint FK32ql8ubntj5uh44ph9659tiih
   foreign key (user_id)
   references users;
alter table user_authorities
   add constraint FK6y0u41do0gynbgvlwnqngjudf
   foreign key (authority_id)
   references authorities;
alter table user_authorities
   add constraint FKhiiib540jf74gksgb87oofni
   foreign key (user_id)
   references users;